### ISSUE TITLE
pip install does not work in Google Colab

### ISSUE THREAD

**Issue by asigalov61** [s-omranpour/DeepNote#1]
Hey Soroush,

I get the following error on !pip install deepnote in Google Colab

Collecting deepnote
  Downloading https://files.pythonhosted.org/packages/1d/10/181b1528c248ac7a5f7ceef84bbd475a74b46f897e919df1f3f0ae7790b9/deepnote-0.0.9.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Manual install works fine.

**Comment by s-omranpour** [comment]
Hey Alex,

thank you for using deepnote. Installing via pip should work fine now. Please try with --upgrade and let me know if there is still any problems.

best,

**Comment by asigalov61** [comment]
Hey Soroush,

Yes, everything seems to be working! :) Thank you so much for your prompt support :)

Alex.
